### ISSUE TITLE
iOS10没效果，写在descriptionWithLocale:(nullable id)locale indent:(NSUInteger)level里才可以？

### ISSUE THREAD

**Issue by JiongXing** [CoderZhuXH/XHLogHelper#2]
我在iOS10使用没效果，写在descriptionWithLocale:(nullable id)locale indent:(NSUInteger)level里才可行，请作者看看？

**Comment by CoderZhuXH** [comment]
好的,回头我看看....

**Comment by CoderZhuXH** [comment]
我这边测试iOS10,- (NSString _)descriptionWithLocale:(nullable id)locale,
和-(NSString_)descriptionWithLocale:(nullable id)locale indent:(NSUInteger)level两个都可以哈...

**Comment by JiongXing** [comment]
啊?? - -||
